#184759888 Setting up the frontend project boilerplate
atlp-rwanda/vikings-ec-fe pull request #1
Opened 2023-03-22 20:11 UTC by Abdden

### What does this PR do?

Starts off the project by initializing React with Webpack and other necessary packages.

### Description of Tasks to be completed?

- Setup an empty react project
- Create the client README file
- Setup react-router  (React-router-dom)

### How should this be manually tested?

1. Clone [repo](https://github.com/atlp-rwanda/vikings-ec-fe.git)
2. Change into the directory `vikings-ec-fe`
3. Checkout to the branch: `chore/setup-react-project-184759888`
4. Run the command `npm install` to install all packages
5. Run `npm start` and your browser will open automatically

#### What are the relevant pivotal tracker stories?

[#184759888](https://www.pivotaltracker.com/story/show/184759888)

[#184759893](https://www.pivotaltracker.com/story/show/184759893)

[#184759891](https://www.pivotaltracker.com/story/show/184759891)

2023-03-22 20:17 UTC, irakozetony approved these changes

2023-03-22 20:55 UTC, Fidela1 approved these changes

2023-03-22 20:59 UTC, nshimiyejayd approved these changes

2023-03-23 07:47 UTC, ncutixavier requested changes

2023-03-23 07:47 UTC, ncutixavier commented on src/routes/index.js
> +export default [home, login];
This approach is not good, please try this approach https://dev.to/jordan_smith/how-to-build-a-react-app-using-react-router-v6-without-create-react-app-4fe3

2023-03-23 11:04 UTC, ncutixavier approved these changes

2023-03-23 11:04 UTC, merged