# 184759901 implement Login
atlp-rwanda/vikings-ec-fe pull request #10
Opened 2023-03-29 13:11 UTC by Aline096

### What does this PR do?
This PR implements Login feature

### Description of Tasks to be completed?
Users should be able to log in

### How should this be manually tested?
- Start [Vikings backend](https://github.com/atlp-rwanda/vikings-ec-bn.git) 
- Clone [repo](https://github.com/atlp-rwanda/vikings-ec-fe.git)
- Change into the directory vikings-ec-fe
- Checkout to the branch: feature/login-184759901
- Run the command `npm install` 
- Run the command `npm run start`

#### What are the relevant pivotal tracker stories?
[#184759901](https://www.pivotaltracker.com/story/show/184759901)

2023-03-31 10:53 UTC, irakozetony approved these changes

2023-03-31 11:05 UTC, fabmukunzi approved these changes

2023-04-03 10:23 UTC, ncutixavier requested changes

2023-04-03 10:23 UTC, ncutixavier commented on src/components/forms/Icon.js
Please rename the file to be specific. What kind of Icon?

2023-04-03 10:23 UTC, ncutixavier commented on src/components/forms/InputField.js
> +          className={`${props.styles} w-full rounded-md p-2 ring-1 ring-gray-300 placeholder:text-gray-400 sm:text-sm my-6`}
`my-6` is not necessary because It's increasing the space between input and errors

2023-04-03 10:23 UTC, ncutixavier commented on src/components/forms/LoginForm.js
> +      password: e.target.elements.password.value,
Since you're using React Hooks form, you don't have to access input values like that. Check this link: https://react-hook-form.com/api/useform/handlesubmit/

2023-04-03 10:23 UTC, ncutixavier commented on src/components/forms/LoginForm.js
> +            {' '}
Why do you need empty string?

2023-04-03 10:23 UTC, ncutixavier commented on src/components/forms/LoginForm.js
> +          )}
This is not needed, Try react notification: https://www.npmjs.com/package/react-notifications-component

2023-04-03 10:23 UTC, ncutixavier commented on src/features/auth/loginSlice.js
> +};
Please ask @fabmukunzi about the following points:

- Axios instances
- Try to use `createAsyncThunk`

2023-04-03 11:00 UTC, ndatumuremyi approved these changes

2023-04-05 20:30 UTC, ncutixavier requested changes

2023-04-05 20:30 UTC, ncutixavier commented on src/components/Navbar.js
> +    <nav className="border-gray-200 py-2.5 rounded dark:bg-gray-900 flex items-center justify-between w-full">
Remove dark background
![image](https://user-images.githubusercontent.com/51375428/230202515-d2e4b165-548d-418f-8e6b-df9f4f7ad3e5.png)

2023-04-05 20:30 UTC, ncutixavier commented on src/store.js
> +import loginSlice from './features/auth/loginSlice';
Replace with loginReducer,

2023-04-05 20:53 UTC, ncutixavier requested changes

2023-04-05 20:53 UTC, ncutixavier commented on src/components/Navbar.js
> +        {navItems.map((navItem) => (
There is some dark styles here

2023-04-05 21:10 UTC, ncutixavier approved these changes

2023-04-05 21:14 UTC, merged