#184759903 Implement seller two factor auth
atlp-rwanda/vikings-ec-fe pull request #13
Opened 2023-04-05 21:30 UTC by fabmukunzi

### What does this PR do?
This PR implements seller two factor auth

### Description of Tasks to be completed?
A seller must send authCode to login
### How should this be manually tested?
- Start [Vikings backend](https://github.com/atlp-rwanda/vikings-ec-bn.git) 
- Clone [repo](https://github.com/atlp-rwanda/vikings-ec-fe.git)
- Change into the directory **vikings-ec-fe**
- Checkout to the branch: `feature/seller-auth-184759903`
- Run the command `npm install` 
- Run the command `npm run start

#### What are the relevant pivotal tracker stories?
[#184759903](https://www.pivotaltracker.com/story/show/184759903)

2023-04-11 09:40 UTC, irakozetony approved these changes

2023-04-11 11:40 UTC, ndatumuremyi approved these changes

2023-04-11 11:44 UTC, Munezeroolivierhugue approved these changes

2023-04-11 16:12 UTC, ncutixavier commented
@fabmukunzi  Resolve the conflicts, and try to raise your coverage

2023-04-13 10:20 UTC, ncutixavier requested changes
How can I get a seller account to test your task?

2023-04-13 10:20 UTC, ncutixavier commented on src/components/forms/2faForm.js
> +      }}
Is this really necessary? What happened when you try the code below:
`<form onSubmit={handleSubmit(onSubmitHandler)}`

2023-04-13 10:20 UTC, ncutixavier commented on src/components/forms/LoginForm.js
> +      if (error.data.message === 'Check your email for verification code') {
- Try using the `includes` function or regex to check if an account is verified or not instead of full text
- Or, you can try the status code

2023-04-13 10:20 UTC, ncutixavier commented on src/features/auth/2faSlice.js
Let's replace `2fa` to `twoFactorAuth`

2023-04-13 10:20 UTC, ncutixavier commented on src/features/auth/2faSlice.js
> +      const id = localStorage.getItem('id');
Can you pass the id in the params instead of local storage?

2023-04-13 20:57 UTC, ncutixavier requested changes

2023-04-13 20:57 UTC, ncutixavier commented on tests/components/2faForm.test.js
Please rename `2fa` anywhere

2023-04-13 21:07 UTC, fabmukunzi commented on src/components/forms/2faForm.js
> +      }}
This event parameter is being used by react hook form in order to prevent its default behavior when form is submitted. when we remove it we  will not be able to see errors on submit

2023-04-13 21:29 UTC, ncutixavier approved these changes

2023-04-13 21:50 UTC, merged