#184821806 User should view items
atlp-rwanda/vikings-ec-fe pull request #15
Opened 2023-04-11 20:45 UTC by nshimiyejayd

### What does this PR do?
- This PR implements the way A user can view and interact with items

### Description of Tasks to be completed?
- A user should be able to view all items
- A user  should be able to view single item
- A user can do different operations on the product like wish, add to cart, edit and delete

### How should this be manually tested?
- Clone [repo](https://github.com/atlp-rwanda/vikings-ec-fe.git)
- Change into the directory vikings-ec-fe
- Checkout to the branch: feature/view-products-184821806
- Run the command npm install
- Run the command npm run dev

### What are the relevant pivotal tracker stories?
[#184821806](https://www.pivotaltracker.com/story/show/184821806) 

### Screenshots
![image](https://user-images.githubusercontent.com/90104592/231279015-29890108-aecf-4cda-a627-55d7a2a60f6e.png)

![image](https://user-images.githubusercontent.com/90104592/231282164-f627d019-98ab-4de1-ad2d-ac397eeb2a21.png)

![image](https://user-images.githubusercontent.com/90104592/231279224-175b957c-8e39-467d-9947-1727ed348367.png)

![image](https://user-images.githubusercontent.com/90104592/231282399-f33ae46e-972f-4424-aac8-abc8ff383882.png)

![image](https://user-images.githubusercontent.com/90104592/231279476-97df13a1-c000-481d-ac8f-223751c7065f.png)

![image](https://user-images.githubusercontent.com/90104592/231281601-85159cc8-a283-4a82-9230-47420e171e31.png)

![image](https://user-images.githubusercontent.com/90104592/231282954-dafe580b-ae3e-4cc9-a54e-8a977f15547c.png)

2023-04-13 06:56 UTC, ndatumuremyi approved these changes

2023-04-13 08:09 UTC, fabmukunzi approved these changes

2023-04-13 08:11 UTC, irakozetony approved these changes

2023-04-20 11:59 UTC, ncutixavier requested changes

2023-04-20 11:59 UTC, ncutixavier commented on src/routes/AppRoutes.js
> +    </Route>
Change the path of the route, 

Get all products: `/products` or `/`
Get single product: `/products/:id`

2023-04-23 22:03 UTC, ncutixavier requested changes

2023-04-23 22:03 UTC, ncutixavier commented on src/components/products/SellerViewSingleProduct.js
> +      })
You must use redux

2023-04-23 22:03 UTC, ncutixavier commented on src/components/products/ProductRatings.js
Why didn't you use the package?

2023-04-23 22:03 UTC, ncutixavier commented on src/components/products/BuyerViewSingleProduct.js
> +  }, [props.products && props.products.id]);
You must use redux

2023-04-23 22:03 UTC, ncutixavier commented on src/assets/index.css
> +  }
You should use tailwind css

2023-04-24 11:12 UTC, ncutixavier commented on src/features/api/customAxios.js
>    return Promise.reject(error);
You forgot to clear the local storage. When the token is expired, you need to remove it from local storage and redirect to login

2023-04-24 11:44 UTC, nshimiyejayd commented on src/components/products/ProductRatings.js
It was harder for me to stylize it and make it working properly

2023-04-24 12:07 UTC, ncutixavier approved these changes

2023-04-24 12:09 UTC, merged