#184759902 implement reset-password
atlp-rwanda/vikings-ec-fe pull request #16
Opened 2023-04-12 07:53 UTC by ndatumuremyi

### What does this PR do?
This PR implements a Reset password

### Description of Tasks to be Completed?
 - Users should be able to reset the password. 

### How should this be manually tested?
1. start [Vikings backend](https://github.com/atlp-rwanda/vikings-ec-bn.git) at port 5000 with FRONTEND_URL=http://localhost:8000 in your env
2. Clone [repo](https://github.com/atlp-rwanda/vikings-ec-fe.git)
3. Change into the directory `vikings-ec-fe`
4. Checkout to the branch: `feature/implement-reset-password-184759902`
5. Run the command `npm install` to install all packages
6. Run the command `npm run start`
7. go to `/auth/forget-password`
8. fill the form then `send`
9. check your email
10. click `reset password button`

#### Screenshot

![ResetPassword](https://user-images.githubusercontent.com/60066777/231389253-dde96074-a067-4b78-af00-817932b56064.png)
![FogetPassword](https://user-images.githubusercontent.com/60066777/231389362-76d7bf0a-8563-473f-bad8-3bd898221b8c.png)

### Figma

![ResetPasswordF](https://user-images.githubusercontent.com/60066777/231389986-4f350d6e-9d31-4586-9d4c-0771784e6efa.png)

![ResetPassword](https://user-images.githubusercontent.com/60066777/231390066-ed1ea0fb-6c5a-4eb5-ae99-e5e9b6145cae.png)

### What are the relevant pivotal tracker stories?
[#184759902](https://www.pivotaltracker.com/story/show/184759902)

2023-04-13 10:29 UTC, ncutixavier commented
- Please check if the backend is deployed successfully because It's showing a timeout error
- Navbar is not functioning, for example, when you click on login, nothing happens.

2023-04-13 11:00 UTC, ncutixavier requested changes

2023-04-13 11:00 UTC, ncutixavier commented on src/components/forms/ForgotPasswordForm.js
> +      }}
Why did you add the event?

2023-04-13 11:00 UTC, ncutixavier commented on src/components/forms/ResetPasswordForm.js
> +        showErrorMessage("Invalid path");
Specify a valid message to the user about where to find a valid path

2023-04-13 11:00 UTC, ncutixavier commented on src/features/auth/forgotPasswordSlice.js
> +      return rejectWithValue(error.response?.data || { message: error.message || 'something went wrong' });
Why do you need to pass all of these values? I think only `error.response` is enough, then other modification can be done under the component catch block

2023-04-13 11:00 UTC, ncutixavier commented on src/features/auth/resetPasswordSlice.js
> +      return rejectWithValue(error.response?.data || { message: error.message || 'something went wrong' });
Same question with `forgotPassword`

2023-04-13 11:00 UTC, ncutixavier commented on src/utils/endpoints.js
> +import { resetPassword } from '../features/auth/resetPasswordSlice';
Is this import necessary?

2023-04-13 14:29 UTC, ndatumuremyi commented on src/components/forms/ForgotPasswordForm.js
> +      }}
event is required by use in order to prevent its default behavior 

`const handleSubmit: (onValid: SubmitHandler<FieldValues>, onInvalid?: SubmitErrorHandler<FieldValues>) => (e?: React.BaseSyntheticEvent) => Promise<void>`

2023-04-13 15:40 UTC, irakozetony approved these changes

2023-04-13 18:16 UTC, fabmukunzi approved these changes

2023-04-14 06:41 UTC, Aline096 approved these changes

2023-04-14 07:39 UTC, ncutixavier approved these changes

2023-04-14 09:02 UTC, merged