feat: update password
atlp-rwanda/vikings-ec-fe pull request #17
Opened 2023-04-13 09:46 UTC by Fidela1

### What does this PR do?

This PR implements update password

### Description of Task to be completed?

- User should be able to update password 

### How should this be manually tested?

1.Start [Vikings backend](https://github.com/atlp-rwanda/vikings-ec-bn.git)
2. Clone [repo](https://github.com/atlp-rwanda/vikings-ec-fe.git)
3. Change into the directory `vikings-ec-fe`
4. Checkout to the branch: `feature/update-password-184759954`
5. Run the command `npm install`
6. Run the command `npm run start`

### What are the relevant pivotal tracker stories?
[184759954](https://www.pivotaltracker.com/story/show/184759954)
#### Screenshots (if appropriate)

2023-04-18 15:49 UTC, irakozetony approved these changes

2023-04-18 17:47 UTC, fabmukunzi approved these changes

2023-04-18 18:14 UTC, ncutixavier requested changes
Remember to squash your commit

2023-04-18 18:14 UTC, ncutixavier commented on src/layout/ProfileLayout.js
> +  console.log('------------------------------------')
Remove all logs and unnecessary comments

2023-04-18 18:14 UTC, ncutixavier commented on src/pages/auth/UpdatePasswordPage.js
> +
`<UpdatePasswordForm/>` was not necessary, Put all the code inside this page.

2023-04-18 18:14 UTC, ncutixavier commented on src/validations/index.js
> +});
Why did you create a login schema? Are you working on the login?

2023-04-18 18:24 UTC, Aline096 approved these changes

2023-04-19 12:07 UTC, ncutixavier reviewed
- Please update your PR description by specifying all steps to test your task

2023-04-19 12:07 UTC, ncutixavier commented on src/pages/auth/UpdatePasswordPage.js
> +       {/* <div className=" md:w-3/5 px-3 border border-grey-400 p-3 flex-grow"> */}
Remove all unnecessary comments

2023-04-19 12:51 UTC, merged