#184759908 Updating and deleting product
atlp-rwanda/vikings-ec-fe pull request #18
Opened 2023-04-14 12:15 UTC by fabmukunzi

### What does this PR do?
Updating Product and Deleting product

### Description of Tasks to be completed?
A seller should be able to update and delete products   from their collection
### How should this be manually tested?
- Clone [repo](https://github.com/atlp-rwanda/vikings-ec-fe.git)
- Change into the directory **vikings-ec-fe**
- Checkout to the branch: `feature/update-product-184759908`
- Run the command `npm install` 
- Run the command `npm run dev`
- Try login as admin **user{email:admin@gmail.com,password:Password@123}**
-  Go to the route **/dashboard/products**
- Click on delete icon to delete
- Click on update icon to update

### What are the relevant pivotal tracker stories?
[#184759908](https://www.pivotaltracker.com/story/show/184759908)
[#184759909](https://www.pivotaltracker.com/story/show/184759909)

2023-04-26 14:51 UTC, irakozetony approved these changes

2023-04-26 15:04 UTC, Munezeroolivierhugue approved these changes

2023-04-26 15:48 UTC, ndatumuremyi approved these changes

2023-04-26 16:28 UTC, ncutixavier commented
Remove all unnecessary file, starting from the icon because they are not belong in your task

2023-04-26 18:11 UTC, ncutixavier requested changes

2023-04-26 18:11 UTC, ncutixavier commented on src/components/forms/updateProduct.js
> +  const extractedDate = `${year}-${month}-${day}`;
Create a util function to handle this functionality. You can get the format you need with `toISOString()`

2023-04-26 18:11 UTC, ncutixavier commented on src/pages/product/updateProduct.js
> +export default UpdateProductPage;
Let's have one file combining this file and the form

2023-04-28 08:10 UTC, ncutixavier commented on src/components/forms/updateProduct.js
This is product related component, not form

2023-04-28 11:35 UTC, ncutixavier approved these changes

2023-04-28 12:30 UTC, merged