#184759907 implement creating product
atlp-rwanda/vikings-ec-fe pull request #20
Opened 2023-04-16 22:28 UTC by Abdden

### What does this PR do?

Updating Product

### Description of Tasks to be Completed?

A seller should be able to update products from their collection

### How should this be manually tested?

- Clone [repo](https://github.com/atlp-rwanda/vikings-ec-fe.git)
- Change into the directory **vikings-ec-fe**
- Checkout to the branch: `feature/create-product-184759907`
- Run the command `npm install` 
- Run the command `npm run dev`
- Try login as a seller
- Click on create product

### What are the relevant pivotal tracker stories?
[#184759907](https://www.pivotaltracker.com/story/show/184759907)

2023-04-17 20:48 UTC, irakozetony approved these changes

2023-04-18 08:41 UTC, Aline096 approved these changes

2023-04-18 08:48 UTC, ndatumuremyi approved these changes

2023-04-26 11:11 UTC, irakozetony approved these changes

2023-04-26 12:01 UTC, ncutixavier requested changes
Please disable your formatter because you're doing unnecessary changes

2023-04-26 12:01 UTC, ncutixavier commented on package.json
> +    "yup": "^1.0.2"
Why are you using two similar packages?

2023-04-26 12:01 UTC, ncutixavier commented on src/components/forms/CreateProductForm.js
> +    console.log(newData);
Remove all unnecessary logs

2023-04-26 12:01 UTC, ncutixavier commented on src/features/api/customAxios.js
> +      'https://vikings-ec-fe-git-feature-create-product-fddcd9-andela-vikings.vercel.app/auth/signin');
You don't have to return a full link, just redirect user to auth route.

Hint: `window.location.href='/auth'`

2023-04-26 12:01 UTC, ncutixavier commented on src/layout/CreateProductLayout.js
- This is not a layout, 
- you can combine this file and create a product form

2023-04-26 12:01 UTC, ncutixavier commented on src/pages/seller/CreateProductPage.jsx
> +export default CreateProductPage;
This is not needed.

2023-04-26 12:01 UTC, ncutixavier commented on src/store.js
> +    category,
Let's follow the same convention

2023-04-26 12:34 UTC, Abdden commented on package.json
> +    "yup": "^1.0.2"
That is not the case.
In fact, it is a single package. I only added another version of the Yup package.

2023-04-26 16:16 UTC, ncutixavier commented on src/store.js
> +    category: category,
They are not supposed to have a similar name. Check above value and try to relate

2023-04-26 16:33 UTC, ncutixavier approved these changes

2023-04-26 16:41 UTC, ncutixavier commented
- In the expiry date, disable the old dates
- After Succesful adding the product, clear the images section and redirect the user to his/her products pages

2023-04-27 12:22 UTC, ncutixavier approved these changes

2023-04-27 12:22 UTC, merged