feat: implement Display Users
atlp-rwanda/vikings-ec-fe pull request #22
Opened 2023-04-20 11:56 UTC by Munezeroolivierhugue

## What does this PR do?

This PR implements displaying users feature

## Description of Tasks to be completed?

Admin should be able to:
- View all users
- Update roles of user
- change status of user

## How should this be manually tested?

- Start [Vikings backend](https://github.com/atlp-rwanda/vikings-ec-bn.git) 
- Clone [repo](https://github.com/atlp-rwanda/vikings-ec-fe.git)
- Change into the directory vikings-ec-fe
- Checkout to the branch: feature/Display-Users-184759911
- Run the command `npm install` 
- Run the command `npm run start

## Screenshots
<img width="496" alt="Screenshot 2023-04-20 at 13 50 54" src="https://user-images.githubusercontent.com/107047654/233357833-ff452a7c-e799-4463-b953-0be826accf99.png">
<img width="865" alt="Screenshot (displaying user) 2023-04-20 at 13 43 35" src="https://user-images.githubusercontent.com/107047654/233357911-0d1db60d-1006-4958-848b-e1d602d5ad8a.png">
<img width="904" alt="Screenshot (update role) 2023-04-20 at 13 44 38" src="https://user-images.githubusercontent.com/107047654/233358105-ba039e78-6745-4406-b3a1-ef565fec1944.png">
<img width="904" alt="Screenshot (change user status)2023-04-20 at 13 44 18" src="https://user-images.githubusercontent.com/107047654/233358142-fb9646da-09ea-4a16-8988-6d3bfe34b7f1.png">

### What are the relevant pivotal tracker stories?
[#184759911](https://www.pivotaltracker.com/story/show/184759911)
[#184759912](https://www.pivotaltracker.com/story/show/184759912)

2023-04-26 08:12 UTC, ndatumuremyi approved these changes

2023-04-26 08:21 UTC, irakozetony reviewed
Remove all consoles
Update PR description to indicate steps for testing it

2023-04-26 09:24 UTC, irakozetony approved these changes

2023-04-26 09:28 UTC, nshimiyejayd approved these changes

2023-04-26 12:20 UTC, ncutixavier requested changes
Please disable your formatter because you're doing unnecessary changes

2023-04-26 12:20 UTC, ncutixavier commented on src/components/DropChildren.js
Please rename this file to be specific with what you're implementing

2023-04-26 12:20 UTC, ncutixavier commented on src/components/forms/users/Table.js
> +    return <div>Loading users...</div>;
Try to use spinner component already created

2023-04-26 12:20 UTC, ncutixavier commented on src/components/products/BuyerViewSingleProduct.js
> +      setIsReviews(true);
Why did you make these changes?

2023-04-26 12:20 UTC, ncutixavier commented on src/features/api/customAxios.js
> +    return (location.href = ` https://vikings-ec-fe-git-feature-display-users-1-67492e-andela-vikings.vercel.app/auth/signin`);
Why did you make these changes?

2023-04-27 12:29 UTC, ncutixavier reviewed
Please rebase, and check the naming of your file and function if they are related to implementation

2023-04-27 12:29 UTC, ncutixavier commented on src/components/DropDown.js
> +const DropChildren = ({
Update the function name

2023-04-27 12:29 UTC, ncutixavier commented on src/components/forms/users/Table.js
- This is users related component, not forms
- The file name and function name should be related to the implementation

2023-04-27 12:29 UTC, ncutixavier commented on tests/components/DropChildren.test.js
Naming has not changed

2023-05-02 11:42 UTC, ncutixavier commented on src/store.js
> +    changeStatus: changeUserStatusSlice,
You import reducer, not slice. Those are reducers, not slices. Please rename that, and if you have any issues you can ask @Abdden

2023-05-02 11:53 UTC, ncutixavier approved these changes

2023-05-02 11:53 UTC, merged