Feature/manage cart 184759919
atlp-rwanda/vikings-ec-fe pull request #23
Opened 2023-04-20 12:53 UTC by ndatumuremyi

### What does this PR do?
This PR implements add/view/remove products from cart

### Description of Tasks to be Completed?
 - User/buyer should be able to add/update & clear items to/from their cart & view the cart. 

### How should this be manually tested?
1. start [Vikings backend](https://github.com/atlp-rwanda/vikings-ec-bn.git) at port 5000 with FRONTEND_URL=http://localhost:8000 in your env
2. Clone [repo](https://github.com/atlp-rwanda/vikings-ec-fe.git)
3. Change into the directory `vikings-ec-fe`
4. Checkout to the branch: `manage-cart-184759919`
5. Run the command `npm install` to install all packages
6. Run the command `npm run start`
7. go to `/cart`

#### Screenshot

![emptyCartImp](https://user-images.githubusercontent.com/60066777/233371837-7e305f3f-2ce4-4f05-97bb-79fcdec0b101.png)

![cartWithProductImp](https://user-images.githubusercontent.com/60066777/233371678-a3341b00-5bd6-4a67-914f-6e3ea404590e.png)

### Figma

![emptyCart](https://user-images.githubusercontent.com/60066777/233371559-a9858f1a-01dc-49b1-b426-bed913b79d0b.png)

![cartWithProductsFigma](https://user-images.githubusercontent.com/60066777/233371128-41c566fa-c40d-43c6-b00c-f73d4141e06a.png)

### What are the relevant pivotal tracker stories?
[#184759919](https://www.pivotaltracker.com/story/show/184759919)

2023-04-27 08:48 UTC, irakozetony approved these changes

2023-04-27 09:12 UTC, fabmukunzi approved these changes

2023-04-27 09:23 UTC, nshimiyejayd approved these changes

2023-04-28 08:03 UTC, ncutixavier requested changes
- You have made many unnecessary changes
- Remove all logs and unnecessary comments

2023-04-28 08:03 UTC, ncutixavier commented on public/images/Shop.svg
Images should be in the assets not public

2023-04-28 08:03 UTC, ncutixavier commented on src/components/cart/CartItem.jsx
> +  };
- Use `try...catch`
- If your redux states are working well you don't need `isLoading`. Please check this

2023-04-28 08:03 UTC, ncutixavier commented on src/components/cart/SetCartQuantity.jsx
> +    productQuantity: addMax(yup.number().required('Quantity is required').min(1))(quantity),
schemas should not be here

2023-04-28 08:03 UTC, ncutixavier commented on src/components/cart/SetCartQuantity.jsx
> +      showErrorMessage(response?.payload?.data?.message || 'Something went wrong');
- Remove all logs
- Try using `try...catch`, to avoid check using type

2023-04-28 08:03 UTC, ncutixavier commented on src/features/api/customAxios.js
> +    return (location.href = '/auth/signin');
Why did you make the changes?

2023-05-02 10:22 UTC, merged