#184759892 setting up sass and redux
atlp-rwanda/vikings-ec-fe pull request #4
Opened 2023-03-23 14:45 UTC by fabmukunzi

### What does this PR do?

Sets up sass and redux

### Description of Tasks to be completed?

- [x] Setup sass
- [] Setup redux

### How should this be manually tested?

1. Clone [repo](https://github.com/atlp-rwanda/vikings-ec-fe.git)
2. Change into the directory `vikings-ec-fe`
3. Checkout to the branch: `chore/setup-sass-184759892`
4. Run the command `npm install` to install all packages
5. Run `npm test`

#### What are the relevant pivotal tracker stories?

[#184759892](https://www.pivotaltracker.com/story/show/184759892)
[#184759889](https://www.pivotaltracker.com/story/show/184759889)

2023-03-24 12:06 UTC, irakozetony approved these changes

2023-03-24 12:09 UTC, Fidela1 approved these changes

2023-03-24 12:37 UTC, ndatumuremyi approved these changes

2023-03-24 18:27 UTC, Abdden commented on webpack.config.js
>        },
If you'd be so kind as to add another block that will be responsible for using image files in the project.
Like : `.svg` , `.png` , `.jpg` , `.jpeg` , `.gif` , etc...

2023-03-24 18:34 UTC, Abdden requested changes

2023-03-24 18:34 UTC, Abdden commented on webpack.config.js
> +        use: ['style-loader', 'css-loader', 'sass-loader'],
If you'd be so kind as to add another block that will be responsible for using image files in the project.
Like : `.svg` , `.png` , `.jpg` , `.jpeg` , `.gif` , etc...

2023-03-24 23:04 UTC, Abdden approved these changes

2023-03-28 07:39 UTC, ncutixavier requested changes

2023-03-28 07:39 UTC, ncutixavier commented on src/features/auth/welcomeAction.js
> +);
- Wrap the above code in `actions` folder
- We need to have Axios instance configuration, refer to this link https://blog.clairvoyantsoft.com/intercepting-requests-responses-using-axios-df498b6cab62

2023-03-28 09:24 UTC, ncutixavier approved these changes

2023-03-28 09:31 UTC, merged