#184759900 implemement google auth
atlp-rwanda/vikings-ec-fe pull request #9
Opened 2023-03-28 17:15 UTC by ndatumuremyi

### What does this PR do?
This PR implements Google authentication

### Description of Tasks to be completed?
 - Users should be able to log in via Google. 

### How should this be manually tested?
1. Clone [repo](https://github.com/atlp-rwanda/vikings-ec-fe.git)
2. Change into the directory `vikings-ec-fe`
3. Checkout to the branch: `feature/implement-google-auth-184759900`
4. Run the command `npm install` to install all packages
5. Run the command `npm run start`
6. go to `/auth`
7. click on the `google` icon

### What are the relevant pivotal tracker stories?
[#184759900](https://www.pivotaltracker.com/story/show/184759900)

2023-03-29 09:30 UTC, Abdden approved these changes

2023-03-29 10:48 UTC, irakozetony approved these changes

2023-03-29 12:49 UTC, Aline096 approved these changes

2023-04-03 08:21 UTC, ncutixavier requested changes
In the tests folder, The folder and file naming is not meaningful. For example, 
- there are folders called `mocs`, `redux.test`, Please change them to be specific
- Some files need to be renamed

2023-04-03 08:21 UTC, ncutixavier commented on src/pages/HomePage.jsx
> +    console.log('backend ', process.env.REACT_APP_BASE_URL);
Remove all logs

2023-04-03 08:21 UTC, ncutixavier commented on src/features/actions/authActions.js
Rename this file to be specific for google

2023-04-03 08:21 UTC, ncutixavier commented on src/features/auth/authSlice.js
Rename this file

2023-04-03 08:21 UTC, ncutixavier commented on src/store.js
> +    auth: authSliceReducers,
Change this key to be specific for google auth

2023-04-03 08:21 UTC, ncutixavier commented on src/utils/Keys.js
This is not needed

2023-04-03 08:21 UTC, ncutixavier commented on src/features/api/customAxios.js
> +  baseURL: `${Keys.BASE_URL}`,
Just get the base URL from  `.env`

2023-04-03 11:44 UTC, ncutixavier reviewed
Change wherever you used `google` to `googleAuth`

2023-04-06 11:30 UTC, Aline096 approved these changes

2023-04-06 11:52 UTC, ncutixavier requested changes
After signup with google, Thisam not being redirect to any page, I've received this JSON
![image](https://user-images.githubusercontent.com/51375428/230369891-739d30cd-dbbf-4008-b1ce-52e54a33d7a1.png)

2023-04-06 11:52 UTC, ncutixavier commented on environments/.env
> +REACT_APP_BASE_URL=https://vikings-ec-bn-mbhd.onrender.com/api/v1
Please don't push env variables.

2023-04-06 11:52 UTC, ncutixavier commented on src/components/GoogleAuthButton.jsx
> +  // const message = 'button';
Remove unnecessary comments

2023-04-06 11:52 UTC, ncutixavier commented on src/features/auth/googleSlice.js
> +      localStorage.setItem('token', payload.token);
Put this in actions

2023-04-06 19:54 UTC, merged